### PR TITLE
Moving ACE dependency to bower

### PR DESCRIPTION
**Pull request by bzz**
As we want an SGA donation process to ASF go smooth, we need to get rid of third-party copyright dependency code ASAP.

ACE on the client-side is the biggest one, and the goal is to use bower to manage such dependencies.

### CODE REVIEW

**Comment by bzz** [comment]
ready to merge

**Comment by anthonycorbacho** [comment]
I tried your PR, compilation works fine but the editor cursor is kind of broken (flashy green border)
screen shot 2015-01-21 at 2 38 50 pm

**Comment by minahlee** [comment]
FYI keybinding-emacs.js file has been customized to fix this problem

**Comment by bzz** [comment]
Hm... is there a way to fix it without customising third-party library? Because it's kind of hard to support then.
@minahlee are you sure that it has to do something with emacs keybindings itself?
Could you point wgich fix are you talking about here https://github.com/NFLabs/zeppelin/commits/master/zeppelin-web/app/scripts/ace/src-min-noconflict/keybinding-emacs.js

**Comment by minahlee** [comment]
@bzz When I work with #279, same thing happened with cursor border color after updating ace-build version, so I had to remove border attribute on .emacs-mode .ace_cursor. in keybinding-emacs.js file
It will be easier to recognize it in #130. Please use Ctrl+F shortcut with search word '.emacs-mode .ace_cursor.{' to find that part.

**Comment by bzz** [comment]
@minahlee how do you think, is this class the only change to back-port?
```css
.emacs-mode .ace_cursor {
  -moz-box-sizing: border-box!important;
  -webkit-box-sizing: border-box!important;
  box-sizing: border-box!important;
  background-color: rgba(0,250,0,0.9);
  opacity: 0.5;
}```

**Comment by corneadoug** [comment]
I'm currently checking the branch out. I also think that css could be applied.
I'm trying it out in dev mode at the moment :)

**Comment by corneadoug** [comment]
Just fixed the cursor problem using some css :)

**Comment by bzz** [comment]
I tested locally and it looks great to me!
screen shot 2015-01-22 at 12 01 25

Good to merge

**Comment by bzz** [comment]
@Leemoonsoo can you review this one please?

**Comment by bzz** [comment]
@swkimme @anthonycorbacho could you guys help reviewing this please?

**Comment by swkimme** [comment]
Sure! I'm building and testing it.

**Comment by Leemoonsoo** [comment]
I'm testing it, too.

**Comment by swkimme** [comment]
Tested, builds & works great. LGTM

**Comment by bzz** [comment]
thank you! As soon as this is merged, I think we are good to send source code to ASF!

**Comment by anthonycorbacho** [comment]
tried too. good to me

**Comment by Leemoonsoo** [comment]
I'm getting 404. 

image

**Comment by bzz** [comment]
@Leemoonsoo 
>I'm getting 404.

Good catch: right now we need explicitly tell which parts of ACE do we include, like keybinding-emacs.js, mode-sql.js, mode-scala.js, etc.

It is done by a 'fake' bower.json that we provide for ace-build (as it is missing https://github.com/ajaxorg/ace-builds/issues/20) in 'override' section of our own [bower.json#32](https://github.com/NFLabs/zeppelin/blob/fix/moving-ace-to-bower/zeppelin-web/bower.json#L32)

Are there any other 'modes' that we are possible missing?

Offtopic: this makes me think that this type of checks (404 on resources) could be automated later throug our integration tests

**Comment by bzz** [comment]
Ready to be merged

**Comment by Leemoonsoo** [comment]
I Tested 404 mode-markdown.js. LGTM

**Comment by bzz** [comment]
Great, thanks! I tested scala, sh, md and sql, no 404s, mergin this one then

**Pull request merged**
