### PR TITLE
issue-339: add interpreter jars into classpath

### PR DESCRIPTION
**Pull request by hunglin**
Not sure if this is the right solution.  I tested it on my local machine and it fixes the issue with registerTempTable.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
This PR probably fix problem with spark 1.2. But i'm not sure it's not bringing any problem for spark 1.1. So until we get better solution, i think it's better to provide user apply this code selectively.

For example
```
f [[ -z "${SPARK_1_2_WORKAROUND}" ]]; then
  addJarInDir "${ZEPPELIN_HOME}/interpreter/spark"
  addJarInDir "${ZEPPELIN_HOME}/interpreter/sh"
  addJarInDir "${ZEPPELIN_HOME}/interpreter/md"
fi
```

furthermore, SPARK_1_2_WORKAROUND can be automatically configured with following code

```
ls ${ZEPPELIN_HOME}/interpreter/spark/spark-core_2.10* | grep 'spark[-]core_2[.]10[-]1[.]2' > /dev/null 2> /dev/null
if [[ $? -eq 0 ]]; then
   export SPARK_1_2_WORKAROUND
fi
```

if we want to apply this fix always automatically for spark 1.2

**Comment by hunglin** [comment]
@Leemoonsoo, thanks for the comments.  I updated this PR with your suggestions.

Could you show me what was the problem of spark 1.1?  Also, in SparkInterpreter.open() (https://github.com/NFLabs/zeppelin/blob/master/spark/src/main/java/com/nflabs/zeppelin/spark/SparkInterpreter.java#L370), it looks like it adds jars from ${ZEPPELIN_HOME}/interpreter/spark to spark context, so why it works in spark 1.1 but not in spark 1.2?

Thanks in advance for your help.

**Comment by Leemoonsoo** [comment]
Why it works in spark 1.1 but not in spark 1.2, i think it is oriented from org.apache.spark.sql.catalyst.ScalaReflection.scala, how they creates JavaMirror for reflection.
Spark 1.2's JavaMirror uses Application classloader and Zeppelin loads all jars for Spark 1.2 in thread context classloader. So spark can not find classes he need.

Because of Zeppelin ship's scala compiler for REPL, any jar need to be loaded into 1) scala compiler, 2) scala compiler runtime, 3) spark cluster. I think sc.addJar() is doing 3).

**Comment by swkimme** [comment]
In my case Zeppelin with Spark 1.2. throws error without this branch.
What if we merge this branch?

**Comment by Leemoonsoo** [comment]
This branch provides possible workaround for Spark1.2 which is completely broken in master branch. 
The workaround adds all interpreter's dependency jars in application classloader, which is originally intended to be loaded with separate classloaders.

While it's providing workaround for broken feature, not affecting to existing feature (conditionally applied) +1 for merging.

**Comment by syepes** [comment]
Thanks for resolving this issue.

**Comment by jongyoul** [comment]
@Leemoonsoo I don't think This PR covers spark-1.3 which will be released by March.

**Comment by Leemoonsoo** [comment]
#364 resolves classloading problem and it also resolves issue of Spark-1.2
While #364 is already merged this PR won't need anymore. so i'm closing it.

Thanks @hunglin for providing really quick and nice fixes! And thanks people reviewing this branch.

**Pull request closed without merging**
