### PR TITLE
Fix MultiEvent Catch in Zeppelin

### PR DESCRIPTION
**Pull request by corneadoug**
## Fixing MultiEvent Listener in Zeppelin

There was an annoying bug in zeppelin:

After moving from one note to another, Running the whole note, or adding new paragraph in a note would be done X times.

There is a simple reason related to angularJs: We have overused $rootScope.$on.

When a $rootScope.$on (Event Listener) is registered, it is registered with the $rootScope. Which means that even if the Controller was flushed after a changing page, the $rootScope is not destroy and the event listener is still register for the old Controller.

### How to Use Events in AngularJS/Zeppelin

* $rootScope.$on event listeners should only be used in MainCtrl which is the top of the App.
* Use $scope.$on for every other controllers to listen to Events
* Use $scope.$emit to send an event to a parent Controller (for example: paragraphCtrl to notebookCtrl)
* Use $scope.$broadcast to send an event to a child Controller (for example: notebookCtrl to paragraphCtrl)
* Use $rootScope.$emit to send an event to a controller that is not your parent (for example: paragraphCtrl to navCtrl), this event should be catch by the MainCtrl with a $rootScope.$on, then sent back to the rightful receiver using $scope.$broadcast.

#### Current ControllerStructure

```
MainCtrl: {
    NavCtrl,
    NotebookCtrl: [ paragraphCtrl, ...]
}
```

### CODE REVIEW

**Comment by corneadoug** [comment]
Ready to Merge, I checked all events and arranges them to use the right $scope or $rootScope

**Comment by swkimme** [comment]
Oh, man it was really annoying. Thanks for fix it!

**Comment by corneadoug** [comment]
I guess it fix the #206

**Comment by Leemoonsoo** [comment]
Awesome!

**Comment by Leemoonsoo** [comment]
I tested this PR and it fixes the multi event catch problem.
However this branch have trouble with updating output and progress of paragraph.

**Comment by corneadoug** [comment]
Can you give an example so that I can reproduce? I don't really understand what you mean by updating output and progress. I tried in multi browser and it was working well

**Comment by Leemoonsoo** [comment]
@corneadoug Can you run any paragraph and see is there any output and progress information updated?

**Comment by corneadoug** [comment]
@Leemoonsoo you were right, one change was missing. It is fixed now.

**Comment by Leemoonsoo** [comment]
Tested and looks good to me! Cool!

**Comment by anthonycorbacho** [comment]
Nice improvement!

**Pull request merged**
