### PR TITLE
Fix CSS on Zeppelin Website

### PR DESCRIPTION
**Pull request by corneadoug**
[X] Fix the horizontal margin and scrollbar when we are on small screen resolution
[X] Fix a few bugs and improve colors on the NavBar Menu

### CODE REVIEW

**Comment by corneadoug** [comment]
## List of bugs found

### Horizontal margin and scroll bar on small screens

__Before:__
screen shot 2015-01-14 at 7 55 56 pm

__After:__
screen shot 2015-01-14 at 8 09 32 pm

### Navbar Menu Style

__Before:__
screen shot 2015-01-14 at 7 56 08 pm

__After:__
screen shot 2015-01-14 at 8 07 27 pm

### Navbar Menu when hovered

__Before:__
screen shot 2015-01-14 at 7 56 29 pm

__After:__
screen shot 2015-01-14 at 8 08 46 pm

### Navbar Menu when current page

__Before:__
screen shot 2015-01-14 at 7 56 43 pm

__After:__
screen shot 2015-01-14 at 8 06 42 pm

### Navbar Menu In normal size when selected and hover

__Before:__
screen shot 2015-01-14 at 7 58 07 pm

__After:__
screen shot 2015-01-14 at 8 05 17 pm

### Button Style and Spacing on Header

__Before:__
screen shot 2015-01-14 at 7 55 46 pm

__After:__
screen shot 2015-01-14 at 8 05 58 pm

**Comment by corneadoug** [comment]
Ready To Merge :)

**Comment by anthonycorbacho** [comment]
Look sexy to me

**Comment by Leemoonsoo** [comment]
Looks awesome!

**Comment by swkimme** [comment]
Great job!

**Comment by bzz** [comment]
Cool!
Can you please merge this to #277 where the lastet work on website update has been going?

**Comment by corneadoug** [comment]
@bzz I'm going to merge it here in gh-pages to update the current website.
You should merge gh-pages to your branch, since it could be easier for you to resolve some potential conflicts

**Comment by bzz** [comment]
Sounds good!

On Thu, Jan 15, 2015 at 1:27 PM, CORNEAU Damien <notifications@github.com>
wrote:

> @bzz <https://github.com/bzz> I'm going to merge it here in gh-pages to
> update the current website.
> You should merge gh-pages to your branch, since it could be easier for you
> to resolve some potential conflicts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NFLabs/zeppelin/pull/285#issuecomment-70038403>.
>



-- 
--
Kind regards,
Alexander.

**Pull request merged**
