### PR TITLE
#369 Package Zeppelin to DEB

### PR DESCRIPTION
**Pull request by jongyoul**
- added profile deb and default control file

### CODE REVIEW

**Comment by swkimme** [comment]
Looks great, but making DEB package is not familiar with me..
how can I test this branch?

**Comment by jongyoul** [comment]
@swkimme This is under construction. You'd better check debian package with `ar` in your mac.

```
# Example
$ JAVA_HOME=`/usr/libexec/java_home -v 1.7` mvn package -Pspark-1.2 -Pdeb -Pbuild-distr -DskipTests
$ ar -x /Users/jl/local/src/g/zeppelin/zeppelin-distribution/target/zeppelin-0.5.0-SNAPSHOT-2646c4d8_all.deb
```

This package will be installed successfully, but, you cannot remove package cleanly yet.

**Comment by jongyoul** [comment]
@swkimme I've installed ubuntu via docker on mac. I tested installing and uninstalling with `dpkg -i zeppelin*.deb` and `apt-get purget zeppelin`. Success! I'll adjust locations of files and add some scripts for starting and stoping zeppelin to make start and stop gracefully

**Comment by jongyoul** [comment]
@swkimme You can test this PR with `-Pdeb`.

```
$ dpkg -i zeppelin*_all.deb
$ service zeppelind start
...
$ apt-get purge zeppelin
```

**Comment by Leemoonsoo** [comment]
Awesome work!
Let me review the changes and try with some Ubuntu and Debian machines.

**Comment by jongyoul** [comment]
All of comments make this PR perfect!! I also start to make RPM package.

**Comment by bzz** [comment]
Great contribution, thank you!

How do you think, is there a way to make this packages Apache BigTop
http://bigtop.apache.org compatible? So one day Zeppelin could be
integrated to BigTop

On Thu, Mar 12, 2015 at 11:16 AM, Jongyoul Lee <notifications@github.com>
wrote:

> All of comments make this PR perfect!! I also start to make RPM package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NFLabs/zeppelin/pull/371#issuecomment-78412102>.
>



-- 
--
Kind regards,
Alexander.

**Comment by jongyoul** [comment]
@bzz I'm not familiar with bigtop, but I think this PR should support bigtop. I'll check it and answer you.

**Comment by Leemoonsoo** [comment]
There were maven profile `-Pbuild-distr` to build tar.gz package. `-Pdeb` is not only generating debian package but also generating tar.gz package, too. @jongyoul is it intended behavior?

And i think we have some options for maven profile

a) -Pbuild-distr generates all package, tar.gz, deb, rpm, etc.
b) Separate profile for separate package (eg. -Pdeb, -Prpm)

Do you have any good idea on this?

**Comment by jongyoul** [comment]
Yes, I think It's a intended behaviour because of using assembly-plugin for building deb. Do you think it's a redundant thing? I'll change this by reconfiguring assembly. And about maven profile, could you change a profile name from build-distr to tgz - or similar meaning - ? `-Ptgz` makes .tar.gz, `-Pdeb` makes .deb, `-Prpm` makes .rpm. I think It could be more clear to understand. And I'll change not to make .tgz when you use `-Pdeb`.

**Comment by Leemoonsoo** [comment]
Sounds good. Then I'll change the profile -Pbuild-distr, to -Ptgz

**Comment by jongyoul** [comment]
@Leemoonsoo I changed configurations for not making tar.gz.

**Comment by Leemoonsoo** [comment]
Tested package generation using -Pdeb, package installation and init script in ubuntu and debian.
All works really well. Really cool!

**Comment by jongyoul** [comment]
@bzz I've checked BigTop for supporting Zeppelin. As a result, on the contrary, BigTop supports Zeppelin. We should make a bigtop patch separately. I'll handle this if you don't have any idea yet. Is it OK?

**Comment by jongyoul** [comment]
@Leemoonsoo Please merge this PR if it doesn't have any problem. New PR about RPM packaging makes conflicts because it will add new codes on a same pom.xml. Thanks.

**Comment by Leemoonsoo** [comment]
I'm merging the PR if there're more further discussions. We can address issue related Bigtop separately.
Thanks!

**Comment by jongyoul** [comment]
@Leemoonsoo Thanks. I think it's good to issue about Bigtop separately.

**Pull request merged**
