### PR TITLE
minor doc update for running on YARN

### PR DESCRIPTION
**Pull request by felixcheung**
Include info on SPARK_YARN_JAR can be HDFS

### CODE REVIEW

**Comment by felixcheung** [comment]
@jongyoul @swkimme Could you please review?

**Comment by jongyoul** [comment]
LGTM. Thanks for fix my typo.

**Comment by swkimme** [comment]
Looks great!

**Comment by jongyoul** [comment]
@swkimme It is ok to merge this PR? I've heard Zeppelin repos moved to apache/incubator-zeppelin. I think @felixcheung should make this PR with same patch under apache/incubator-zeppelin. How do you think of it?

**Comment by swkimme** [comment]
@jongyoul 
Oh, you're right. 
I guess we need to create this PR again for apache/incubator-zeppelin repo. 
@felixcheung can you do that?

**Comment by felixcheung** [comment]
Absolutely! Created https://github.com/apache/incubator-zeppelin/pull/2

**Pull request merged**
