### PR TITLE
Fix Zeppelin web build

### PR DESCRIPTION
**Pull request by anthonycorbacho**
This PR is about simplifying the pom (by updating the frontend-maven-plugin plugin) plus doesn't reinstall node, npm and bower components for every build.

Fix also the imagemin error `lib64/libc.so.6: version GLIBC_2.XX' not found` on Linux

### CODE REVIEW

**Comment by bzz** [comment]
New version of eirslett/frontend-maven-plugin implements [running bower](https://github.com/eirslett/frontend-maven-plugin#running-bower) and [running grunt](https://github.com/eirslett/frontend-maven-plugin#running-grunt) so this PR take advantage of it which simplifies pom.xml
Looks great to me!

**Comment by anthonycorbacho** [comment]
For the issue #295, the root pom is a mess and it is really hard to understand what is going on there and the `pluginManagement` somehow trigger the webapp to be build 2 time.
The only way I found is to comment out the 
```
 <parent>
    <artifactId>zeppelin</artifactId>
    <groupId>com.nflabs.zeppelin</groupId>
    <version>0.5.0-SNAPSHOT</version>
  </parent>
```
For me it is totally fine because
 * Zeppelin web app is self contain and doest require any dependency from the parent
 * Zeppelin web already have a checkstyle (JSHints)

Now the webapp only need `~54s` to build.....

Any advice or cleaner way to solve this issue?

**Comment by anthonycorbacho** [comment]
Well I think this PR is ready to go.
I tested it againts OSX, centOS 6.5 and Ubuntu and compiletion worked fine.
Also updated the readme file.

@Leemoonsoo  can you take a look and tell me whats bother you?

**Comment by anthonycorbacho** [comment]
Just for the sport:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin .......................................... SUCCESS [2.208s]
[INFO] Zeppelin: Zengine ................................. SUCCESS [3.153s]
[INFO] Zeppelin: Spark ................................... SUCCESS [2.585s]
[INFO] Zeppelin: Markdown interpreter .................... SUCCESS [1.226s]
[INFO] Zeppelin: Shell interpreter ....................... SUCCESS [1.134s]
[INFO] Zeppelin: web Application ......................... SUCCESS [53.121s]
[INFO] Zeppelin: Server .................................. SUCCESS [2.950s]
[INFO] Zeppelin: Packaging distribution .................. SUCCESS [0.297s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:06.917s
[INFO] Finished at: Thu Jan 22 20:53:08 KST 2015
[INFO] Final Memory: 53M/669M
[INFO] ------------------------------------------------------------------------
```

**Comment by anthonycorbacho** [comment]
Can someone review this PR?

**Comment by Leemoonsoo** [comment]
Great. It works perfectly for me, but let me test little bit more with different conditions.

**Comment by anthonycorbacho** [comment]
@Leemoonsoo sure.

**Comment by corneadoug** [comment]
Tested on Mac OSX after git clean and bower/node cache cleaned, worked well even though I don't get the same compilation speed (2:35:271 for me), but it is clearly faster and there is no duplicate anymore on the web part

**Comment by anthonycorbacho** [comment]
@corneadoug of course the build 'speed' will depends on your hardware :)

**Comment by Leemoonsoo** [comment]
Tested with non-root / root user. with/without build-distr. Great work! LGTM!

**Comment by anthonycorbacho** [comment]
So it is good to be merge?

**Comment by Leemoonsoo** [comment]
I think it's good to go.

**Pull request merged**
