### PR TITLE
Enhancement/typescript automation

### PR DESCRIPTION
**Pull request by corneadoug**
Branch to help #321
- [x] - Checking the build system
- [x] - Fixing grunt serve
- [x] - Replacing JSHint with TSLint
- [x] - Fix TSLint errors
- [ ] - Try yoman .ts creation
- [ ] - Help with documentation + documentation of tools and plugin

### CODE REVIEW

**Comment by corneadoug** [comment]
I deactivated some rules from the original TSLint configuration because there was too many errors and TSLint is now a blocker in the build.

We will have to discuss if we reactivate them in the future:
* no-use-before-declare
* no-unused-variable
* no-duplicate-variable
* typedef check

**Comment by swkimme** [comment]
AWESOME job! You should've spent many of your weekend for this job!
I'll try it right now.

**Comment by swkimme** [comment]
I've tried yeoman ts creation and it works well. 
But the process is quite complex. :(
You need to download yeoman and angular-generator with ts, and manually link it.

**Comment by corneadoug** [comment]
I saw that you documented the way to include the plugin.
Just like yoman is not part of the build, other tools or plugin that can help developers should be documented, it's like we can include them for the user.

125 TSLint errors left hahahaha

**Comment by swkimme** [comment]
Let me correct the tslint errors. IntelliJ will help me!

**Comment by corneadoug** [comment]
It's okay, I'm already doing it

**Comment by swkimme** [comment]
OK, cheers!

**Comment by corneadoug** [comment]
Fixed the TSLint errors, I removed some more rules:
* interface-name
* empty-block

**Comment by corneadoug** [comment]
@swkimme I think we should get the option 'typedef check' back so that we can pass the whole app in typescript.
However there is some problems:
* The amount of errors will be huge
* We will need to create classes for everything, where do we place them? Because it will be a lot of lines.

**Comment by swkimme** [comment]
@corneadoug 
If classes are small, we can just put it in a file like types.ts, 
and when classes get bigger, we can divide them, like notes.ts, paragraphs.ts, .. 
and if it get bigger, we can make a package-like dir structure and put class files under them, 
like paragraph/paragraph.ts, paragraph/config.ts, .. 

I've got some big project using Typescript for reference. Plz take a look at!
https://github.com/mozilla/shumway

**Comment by corneadoug** [comment]
For what I see from that repo, all variable declarations do not need a type?
Should we include types only when they are in function parameters?

**Comment by swkimme** [comment]
You have to declare class or interface 'members' with type, 

and for just a variable, you don't need to put type everytime.

(O)
interface A {
  a: string;
}
(O)
var b = 1 
(O)
var b: number = 1 

Also for function parameters, Typescript has a type inference system for it, you don't need to type it everytime.

**Comment by corneadoug** [comment]
@swkimme Since you know better about typescript synthax, can you change 'typedef' to true in tslint.json, run ```grunt tslint``` and see which rule of typedef we should keep?

**Comment by swkimme** [comment]
@corneadoug 

Positive for call-signature and parameter, 
it will change our codes like this and it's safer and better.

-  function getWebsocketProtocol(blah) {
+  function getWebsocketProtocol(blah: number): string {

but negative for property and variables. 
It will make our code too much verbose and hard to code.
I think 
var b = 1 
is just OK, and still we can optionally supply types like 
var b: number = 1
if we really need to do it. 

Also for function parameter, I'd like to leave it optional since sometime it will be quite too much verbose when we got some code snippets and paste it. 

So, what if we just add call-signature typedef only?
that means, from now we need to do like
-      var retryRenderer = function() {
+      var retryRenderer = function(): void {

Or if you prefer adding parameter typedef, I'm OK with it.

**Comment by swkimme** [comment]
@corneadoug 
Damien, let's wrap up this things!

**Comment by Leemoonsoo** [comment]
Any updates?

**Comment by swkimme** [comment]
I'm OK with merge it, without yoman.

**Comment by corneadoug** [comment]
Didn't got time to work on it recently, there is also some tslint errors left with the rules we set. I will try to finish it this week.

**Comment by corneadoug** [comment]
@swkimme I have a problem with both grunt-ts and grunt-typescript
It compile without any typescript errors, however when the IDE is compiling the typescript, it brings tons of errors. Seems like nobody run the pre-processors. Do you have any idea?

**Comment by corneadoug** [comment]
@swkimme okay, nevermind, errors on IDE suddenly disappeared...

**Pull request closed without merging**
