### PR TITLE
Support Spark 1.3

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Spark 1.3 is released.
This PR make Zeppelin work with Spark 1.3.

* [x] Add profile
* [x] Make Zeppelin build with Spark 1.3
* [x] Take care of SchemaRDD -> DataFrame 
* [x] Test on cluster environment

### CODE REVIEW

**Comment by swkimme** [comment]
You're moving so fast!

**Comment by Leemoonsoo** [comment]
Ready to be merged!

image

Note that implicit conversion from RDD -> DataFrame is not working.
ie. following code is failing
```Scala
case class Person(name:String)
val person = sc.parallelize(List(Person("hello"), Person("world")))
person.registerTempTable("person")  // fails
```
The same problem exists in spark-shell, too.

**Comment by swkimme** [comment]
Great demo! +1 for merge.

**Comment by syepes** [comment]
+1 will be test driving 1.3 this week

**Comment by Leemoonsoo** [comment]
According to https://spark.apache.org/docs/latest/sql-programming-guide.html#starting-point-sqlcontext, HiveContext is preferable one than using SparkContext.

I pushed one more change that if HiveContext (hive related dependency is loaded) is available, use it instead of SparkContext

**Comment by syepes** [comment]
@Leemoonsoo have you tried:

    person.toDF.registerTempTable("person")

**Comment by syepes** [comment]
@felixcheung I am with you, It would be better to leave it up to the user to make the choice. I personally use the CassandraSQLContext

**Comment by Leemoonsoo** [comment]
@syepes Thanks for letting know a way to registerTempTable.

https://github.com/apache/spark/blob/v1.3.0/repl/scala-2.10/src/main/scala/org/apache/spark/repl/SparkILoop.scala#L1022
spark's createSQLContext() api always creates HiveContext, creates SQLContext when it fails.
so i tried to the same in Zeppelin. But i agree on giving user an option.

Then, @felixcheung, @syepes, how about bringing [zeppelin.spark.useHiveContext](https://github.com/NFLabs/zeppelin/commit/c7f7f8f088b27163ce2962fc15bcb3440dc5dd45#diff-35eac9f6d4a90510c68f8a111c5e64ceL57) property back with default value 'true'? Which is just removed in this PullRequest. Previously, default value was 'false'

**Comment by syepes** [comment]
@Leemoonsoo No problem, the usage of the useHiveContext is a good alternative.
I will be updating my fork that has the useCassandraSqlContext option with you changes.

Thanks for the work on 1.3

**Comment by felixcheung** [comment]
@Leemoonsoo  sounds good to me too.

**Comment by geekflyer** [comment]
@Leemoonsoo I've tried to execute your very exact same example, however it appears the df val is not passed along to the sql editor and I get the message `no such table List(df)`.

I'm running running spark standalone with 2 workers. Spark version 1.3.0 . 
Zeppelin was built using `mvn clean package -Pspark-1.3 -Dhadoop.version=2.2.0 -Phadoop-2.2 -DskipTests` from the spark_1.3 branch.

Any idea what causes the problem?

image

**Comment by Leemoonsoo** [comment]
@geekflyer 
Thanks for trying this branch. You need register DataFrame as a table before making sql query, like
```
df.toDF.registerTempTable("df")
```

**Comment by Leemoonsoo** [comment]
`zeppelin.spark.useHiveContext` property is restored with defaultValue 'true'.
I'm merging it if there're no more issues on this branch!

**Comment by swkimme** [comment]
+1 for merge

**Comment by geekflyer** [comment]
@Leemoonsoo Thanks for you help. Now it works completely fine :-)

**Pull request merged**
