### PR TITLE
Replace jQuery to Angular Way

### PR DESCRIPTION
**Pull request by corneadoug**
As a first step into removing as much jQuery as possible :)

Since jQuery.extend was used to do deep copy only (and not extend an object), I replaced it with angular.copy

I ran Zeppelin using Websocket to check that update between two web browser was still working, but would love to have other people checking it out

### CODE REVIEW

**Comment by swkimme** [comment]
Great job, let's go until all of jQuery codes are removed!!

**Comment by anthonycorbacho** [comment]
lets it burn to the ground

**Comment by corneadoug** [comment]
If anybody sees some jQuery that we should change, please list it in this PR

**Comment by anthonycorbacho** [comment]
Look great to me
you can merge it :)

**Comment by anthonycorbacho** [comment]
Look good to me

**Comment by corneadoug** [comment]
Since a lot of Branches were merged to master, I had to merge master in this branch and fix some conflicts (in notebook.js). Instead of simply fixing the conflict, I refactored the getInterpreterBindings() into a function and changed the name as initializeInterpreter(). @Leemoonsoo since you implemented the getInterpreterBindings(), can you check that branch?

**Comment by Leemoonsoo** [comment]
@corneadoug Refactoring around initializeInterpreter changes how it works. Originally, getInterpreterBinding is invoked and some function is passed as a parameter. Now, getInterpreterBinding is not called from initializeInterpreter().

**Comment by corneadoug** [comment]
@Leemoonsoo Just Fixed it

**Comment by corneadoug** [comment]
Ready to Merge, any new feedback?

**Comment by Leemoonsoo** [comment]
Let me test it!

**Comment by Leemoonsoo** [comment]
Tested and LGTM

**Pull request merged**
