### PR TITLE
PySpark

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Supporting python discussed in #240.

This PR adds PySparkInterpreter for python support.
It leverage py4j for the integration between python and Zeppelin.

Here's basic usage of newly implemented %pyspark.
image

to use it, have to provide _spark.home_ property at interpreter setting. which is location of spark distribution.

image

This is not complete code, work still in progress. But the basics are working and you can taste Python on Zeppelin

Todo

* [x] basic support
* [x] job canceling
* [x] job progress
* [x] sparksql
* [x] dynamic form creation
* [x] multiline statements with indentation

Any feedback is welcoming

### CODE REVIEW

**Comment by swkimme** [comment]
Awesome!
I'll promote this to Korean Spark community, many's are waiting for Python Zeppelin!!

**Comment by iz4blue** [comment]
AWESOME!!!

**Comment by jongyoul** [comment]
+1

**Comment by cdfhuang** [comment]
Very exciting feature! Great work!!!

**Comment by felixcheung** [comment]
Cool!
I tried but couldn't get simple stdin/stdout redirect to work, from a quick glance you are doing that manually at zeppelin_pyspark.py. Also seems like it will share the SparkContext from the JVM (very cool)

**Comment by Leemoonsoo** [comment]
@felixcheung
Could you tell me stdin/stdout redirect problem you have?

And yes! It's sharing SparkContext and SQLContext. 
It's going to be even cooler if it shares RDD object.

**Comment by felixcheung** [comment]
@Leemoonsoo  

I started prototyping this by shelling out `python` and redirecting stdin & out from the main zeppelin process. python seemed to be explicitly detecting whether it was running under an interactive shell, by which it was not returning any output (probably was not eval on any code) until either ctrl-c or it hit some syntax error. It was strange - the same pattern worked for other program or command I tested with, but not python.

Here's the core of the code:
```
        DefaultExecutor executor = new DefaultExecutor();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        executor.setStreamHandler(new PumpStreamHandler(outputStream));

        executor.setWatchdog(new ExecuteWatchdog(commandTimeOut));
        try {
            int exitValue = executor.execute(cmdLine);
        } catch (ExecuteException e) {
            ...
        } catch (IOException e) {
            ...
        }
```

**Comment by felixcheung** [comment]
@Leemoonsoo 
One thing to note, are these PySpark specific env var, set by the shell script pyspark:

`PYSPARK_PYTHON` - this is the path to the python command, this gets passed to the workers in cluster mode and so must be the same path on the driver (zeppelin) and all workers (and must be the same Python version)

`PYSPARK_DRIVER_PYTHON` - not applicable in this case, this would be the path to the python command or any shell (ipython) for the driver

`PYTHONPATH` -  this should be set to $SPARK_HOME/python/lib/py4j-0.8.2.1-src.zip:$SPARK_HOME/python/:$PYTHONPATH

**Comment by Leemoonsoo** [comment]
@felixcheung Thanks for the note. I added them in _conf/zeppelin-env.sh.template_. 

Short comments from me is 
`PYTHONPATH` is constructed within interpreter. PySparkInterpreter is automatically construct `PYTHONPATH` based on spark.home property. So, in current implementation, user does not need to set this environment variable unless he have any extra module want to include.
And It looks like if identical version of python is in `PATH` in all cluster node, `PYSPARK_PYTHON` can be committed.

**Comment by Leemoonsoo** [comment]
This branch is ready. Please review and test.

Here's summary

##### Interpreter
%pyspark is the keyword to use PySpark.
open(), close(), interpret(), cancel(), getProgress() implemented.
completion() is not going to be handled in this PR.

##### Context 
Zeppelin automatically creates and expose following variables.

sc - SparkContext. 
sqlc - SQLContext. 
z - ZeppelinContext.

the contexts are shared with scala environment.

**Comment by Leemoonsoo** [comment]
For fun, i'm attaching one screenshot that playwith matplotlib

image

**Comment by swkimme** [comment]
Even looks greater than Scala version. 
Do I need to move to Python? :)

**Comment by felixcheung** [comment]
@Leemoonsoo A slight possible issue is that bin/pyspark script set PYSPARK_PYTHON and it prefers python2.7 ([here]). However is it not matched by the Scala/JVM code - there it prefers python ([there]). If PYSPARK_PYTHON is left unset, this could cause problem in cluster mode when on the driver node multiple python versions are installed (eg. python 2.6 as python, python 2.7 as python2.7 - this is likely a very common config for Redhat/Centos)

[here]:https://github.com/apache/spark/blob/517975d89d40a77c7186f488547eed11f79c1e97/bin/pyspark
[there]:https://github.com/apache/spark/blob/3f941b68a2336aa7876aeda99865e7c19b53bc5c/core/src/main/scala/org/apache/spark/deploy/PythonRunner.scala

**Comment by Leemoonsoo** [comment]
@felixcheung
Thanks for clarifying issue and usage of PYSPARK_PYTHON.

@swkimme 
Instead of move, you can both use Scala and Python at the same time.

Here's one example that create rdd and register temp table from python and query the same data in scala.
image

Another example that exchange object between python and scala.
image

**Comment by felixcheung** [comment]
@Leemoonsoo Awesome demo!

**Comment by Leemoonsoo** [comment]
I'm merging if there're no more discussions.

**Comment by Leemoonsoo** [comment]
I have pushed a support for pyspark 1.3.0.
pyspark in Zeppelin now works with Spark version 1.2.x, 1.3.x.  (not 1.1.x and below)

**Comment by anthonycorbacho** [comment]
@Leemoonsoo `pyspark in Zeppelin now works with Spark version 1.2.x, 1.3.x. (not 1.1.x and below)` i guess we should let a note somewhere for people?

**Comment by Leemoonsoo** [comment]
@anthonycorbacho I added a short comment to conf/zeppelin-env.sh.
PySparkInterpreter detects current spark version and print error message when it is not supported version.

**Comment by Leemoonsoo** [comment]
I'm merging it if there're no more discussions

**Comment by Leemoonsoo** [comment]
Merged manually.

**Comment by DrSleep** [comment]
I have got an error when I try to collect some data from scala in pyspark (Py4JError(u'org.apache.spark.api.python.PythonRDDcollectAndServe does not exist in the JVM')).

First, I created some dummy RDD in Scala, then I registered it as a temp table and used %pyspark with sqlc.sql to get this data in python. But I couldn't look either at the first row of the data or at the whole data. 
screenshot from 2015-04-01 11 21 11

**Comment by felixcheung** [comment]
Same error I run into earlier. My issue was with mismatch build of spark - is it possible that you are building Zeppelin with the spark-1.3 profile (which brings in the official 1.3 release) but you have Spark_home pointing to a custom Spark build from the branch-1.3 branch from github? The method of the error below (collectAndServe) only exists post the official 1.3 release.

--- Original Message ---

**Comment by DrSleep** [comment]
Yepp, that was the case! 
Thank you!

**Comment by felixcheung** [comment]
Great! I'm glad that helps

--- Original Message ---

**Pull request merged**
