### PR TITLE
Updated frontend-maven-plugin to version 0.0.23

### PR DESCRIPTION
**Pull request by seckin206**
Solution for issue #403

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
@seckin206 Thanks for the contribution!

Zeppelin recently has moved to Apache and this repository will not accept update anymore. Could you recreate your pull-request to https://github.com/apache/incubator-zeppelin?

**Comment by seckin206** [comment]
will do

**Comment by Leemoonsoo** [comment]
Thanks!

**Comment by seckin206** [comment]
Pull request submitted.

**Comment by seckin206** [comment]
Closing pull request here.

**Pull request closed without merging**
