### PR TITLE
Single SparkContext parallelization

### PR DESCRIPTION
**Pull request by cdfhuang**
#331 

Using multiple SparkInterpreters causes an exception because each SparkInterpreter creates its own SparkContext, but there can't be more than 1 SparkContext in one JVM. This PR adds some logic to share a SparkContext by creating a pool for each SparkInterpreter. Ideally, each interpreter runs in its own JVM, but I see that's under consideration #278, so this is intended as a temporary workaround until that happens. 

There is one problem though. If multiple SparkInterpreters share the same SparkContext, it's not possible to close the SparkContext when closing one of the SparkInterpreters, so once a SparkContext is created, changes can't be made. Are there comments about how to best address this?

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for deep consideration about internal.

To handle that problem, i think counting number of reference to SparkContext and close SparkContext when they become Zero, is one available way. That counter can increase value inside of open() and decrease it's value inside of close().

By the way, isn't it already possible to use single SparkContext by creating single interpreter setting and bind it across all notebooks?

**Comment by cdfhuang** [comment]
Thanks for the comments. I was considering the counter idea just earlier. It does mean still mean that a SparkContext can't be changed until all interpreters are closed though.

It is possible to use a single SparkContext by binding a single interpreter to multiple notebooks. But the problem I'm trying to address with this PR problem is providing concurrent execution when there are multiple Spark interpreters. Since all the interpreters are in the same JVM, they can't have their own SparkContext, and must share it.

Binding a single interpreter to all notebooks also has the problem where all jobs go into the same pool, so it's one one fewer way of sharing resources to different jobs. With different interpreters, each with a different pool (or SparkContext), there is more control on resource sharing.

**Comment by Leemoonsoo** [comment]
@cdfhuang Thanks for explanation. I think using single SparkContext to leverage it's fair scheduler is good idea. I tested this code and found a problem.

Let's say i have SparkInterpreter _a_ and _b_ and they use singleton SparkContext. Each SparkInterpreter embeds their own scala compiler. So any lambda function, class definitions are dynamically compiled to *.class file. There're http server for serving these *.class file to spark worker. The problem is SparkWorker always looking for class from class server in SparkInterpreter _a_ (if _a_ initialized first).
Therefore for some lambda function defined in _b_, Spark worker raise ClassNotFoundException.

**Comment by cdfhuang** [comment]
@Leemoonsoo  Thanks for your explanation. I did some investigation, and it seems like it's not possible to get around the ClassNotFoundException. Each SparkIMain created by a SparkInterpreter will create its own HTTPServer. But the shared SparkContext is only aware of one of those HTTPServers (set by `spark.repl.class.uri`).

So I guess this PR will not work, unless there is another workaround. Ideally, I think #278 is the way to solve the concurrent SparkInterpreter issue though.

**Pull request closed without merging**
