### PR TITLE
Scatter chart

### PR DESCRIPTION
**Pull request by minahlee**
This PR introduces zeppelin scatter/bubble chart.

Here is the preview.

### CODE REVIEW

**Comment by swkimme** [comment]
Awesome! I'll test it!

**Comment by swkimme** [comment]
I got some problem running this branch.
2015-03-09 3 11 56 pm

**Comment by swkimme** [comment]
It was my mistake! I was building old ```scatter_chart``` branch.. I tested and works great!

**Comment by minahlee** [comment]
Thx for the feedback! I was going to ask you how can I reproduce the error.
please let me know if another error pops up with new scatter chart branch :)

**Comment by swkimme** [comment]
I have a suggestion. 

Currently the chart is displaying ```group``` when I hover mouse on a point. 
It will be cooler if we display ```size```, too!

2015-03-10 4 28 00 pm

**Comment by minahlee** [comment]
Actually that is what I wanted to do from the beginning, but I could not find solution...
I will dig into it more and add that feature in another PR if I find the way to do it!

**Comment by swkimme** [comment]
Then it looks good to me! But we also need to write Typescript ver. codes for #321. 
I can help you if you have problem writing Typescripts.

**Comment by minahlee** [comment]
Ok I will merge this PR on #321 too.

**Comment by corneadoug** [comment]
I know how to print value instead of group :)

**Comment by corneadoug** [comment]
### If the Size is not a valid type of value, we don't show the size
screen shot 2015-03-10 at 5 40 15 pm

### If the Size is a valid type of value, we show the Size in the tooltip
screen shot 2015-03-10 at 5 39 56 pm

**Comment by swkimme** [comment]
@corneadoug 
You're the best!

**Comment by felixcheung** [comment]
Cool - what's the best way to get test data to test this out? I see a SQL statement, so any table/SQL output would work?

**Comment by corneadoug** [comment]
@felixcheung You can test it with any notebook you already have.
Scatter Chart is shown as an additional button on the visualization graph switch bar, it is on the far right of that bar.

**Comment by Leemoonsoo** [comment]
Awesome Job! Looks great.

Can we merge it into master first and then create typescript version for #321?

**Comment by swkimme** [comment]
@felixcheung 
Try this!
```
import scala.util.Random

val rdd = sc.parallelize(0 to 100).map{
  x => 
  val r = new Random
  (r.nextInt(100), r.nextInt(100), r.nextInt(4), r.nextInt(5))
}
rdd.registerTempTable("test")
```

**Comment by swkimme** [comment]
@Leemoonsoo 
Sure, but at least I'd like to create an issue for that.

**Comment by Leemoonsoo** [comment]
While issues are created for typescript, i'm merging it!

**Comment by swkimme** [comment]
Let's merge it!

**Pull request merged**
