### PR TITLE
Fix auto completion bug by updating ace-build

### PR DESCRIPTION
**Pull request by minahlee**
This PR fixes auto completion bug that doesn't work right after '.' character. (Issue #248)

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
I tested and it works really well.
What a cool fix!

**Comment by swkimme** [comment]
SUPER COOL, Great!

**Comment by swkimme** [comment]
BTW, I found really working-well scala editor, (someday I talked with @Leemoonsoo )
http://www.scala-js-fiddle.com/
https://github.com/lihaoyi/scala-js-fiddle
That sends the codes to server and compiles the source code to supply good auto completion.

And another idea for our case is, 
Autocompletion in local words will work better if we share completer context across all paragraphs in a note. 
(currently, if I change paragraph, I cannot use words in another paragraphs)

**Comment by Leemoonsoo** [comment]
Nice catch, sharing completer context across all paragraph for local word is i think next job for improving autocompletion.

**Comment by bzz** [comment]
@minahlee which version of ace-build does Zeppelin use now?

**Comment by minahlee** [comment]
@bzz yes 1.1.8! You can check it on bower.json under zeppelin-web

**Pull request merged**
