### PR TITLE
Add Tutorial Notebook

### PR DESCRIPTION
**Pull request by swkimme**
Added tutorial note for newbies. it's look like:
screen shot 2015-02-13 at 11 23 59 pm
screen shot 2015-02-13 at 11 24 39 pm

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Cool!

**Comment by felixcheung** [comment]
+1!

**Comment by bzz** [comment]
Looks great

**Comment by swkimme** [comment]
Thanks! merging it

**Pull request merged**
