### PR TITLE
Sync versions with spark

### PR DESCRIPTION
**Pull request by jongyoul**
Fixed jackson dependencies for using it and changed version to 1.9.13. and Adjusted indentations

### CODE REVIEW

**Comment by jongyoul** [comment]
This is very simple changes. We should try to find a easy way to sync properties with spark. It's a little bit time consuming job.

**Comment by jongyoul** [comment]
Use this link for check real changes without indentations https://github.com/jongyoul/zeppelin/commit/54fab52d1fcc5f02bd579d9d8863633d0e078d77

**Comment by anthonycorbacho** [comment]
Indentation is 2spaces

**Comment by jongyoul** [comment]
@anthonycorbacho Yes, I fixed indentation to 2 spaces. some lines was tab and 4spaces and so on...

**Comment by jongyoul** [comment]
If I make a mistake, feel free to talk to me.

**Comment by felixcheung** [comment]
LGTM...

**Comment by Leemoonsoo** [comment]
Thanks, LGTM!

**Comment by jongyoul** [comment]
Could anyone please merge this PR?

**Comment by Leemoonsoo** [comment]
We're in the middle of code transition to ASF. So i'm afraid we can not merge it right now. I'll discuss about it in the mailing list.

**Comment by jongyoul** [comment]
@Leemoonsoo Ok. You have a plan to merge something after moving to ASF, don't you?

**Comment by jongyoul** [comment]
I've moved this PR to apache/incubator-zeppelin#1

**Pull request closed without merging**
