### PR TITLE
Remove docs related part since zeppelin-docs module is removed

### PR DESCRIPTION
**Pull request by minahlee**
#289 PR occured below warning.
java.io.FileNotFoundException: /Users/zeppelin/zeppelin-server/../zeppelin-docs/src/main/swagger
This PR fixes it by removing docs related part.

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
You should also consider to remove the swagger dependencies too. We dont need to add more dependencies if there is no use for them.

**Comment by Leemoonsoo** [comment]
@minahlee FYI, we have swagger dependencies on zeppelin-server/pom.xml

**Comment by Leemoonsoo** [comment]
I created #332 to address issue about dropping swagger dependency.
While this PR nicely removes error, It looks good to me!

**Comment by echarles** [comment]
To complete the picture, why the docs have been removed? Would it make sense to revive the zeppelin-docs webapp?

**Comment by Leemoonsoo** [comment]
@echarles #289 has short description about why it has been removed.

**Comment by Leemoonsoo** [comment]
If there're no more discussion, i'm merging it.

**Pull request merged**
