### PR TITLE
Gh pages update new feature

### PR DESCRIPTION
**Pull request by minahlee**
Ready to merge

### CODE REVIEW

**Comment by bzz** [comment]
Looks great to me. 
May be even worth a special notice in @dev mailing list that python support has been implemented and merged too!

**Comment by bzz** [comment]
BTW how do you think, does it resolve #392 ?

**Comment by Leemoonsoo** [comment]
LGTM.
and let's notice @dev about pyspark after resolve #391

**Comment by jongyoul** [comment]
Wow, good example!!

**Pull request closed without merging**
