### PR TITLE
Fix wrong user mailing list subcription link

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Fix wrong user mailing list subcription link

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
Moon, dot you think it is better to change this by 
```
**Mailing List:** [User and Dev mailling list](http://zeppelin.incubator.apache.org/community.html)<br/>
```

**Comment by Leemoonsoo** [comment]
@anthonycorbacho 
You mean README.md?

**Comment by anthonycorbacho** [comment]
yes

**Comment by Leemoonsoo** [comment]
@anthonycorbacho I agree. i'll push those changes to #284

**Comment by anthonycorbacho** [comment]
Awesome!

**Comment by Leemoonsoo** [comment]
I'm pushing this chances to https://svn.apache.org/repos/asf/incubator/zeppelin/site

**Pull request merged**
