### PR TITLE
Fix Integration Test

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Integration Test not always succeeding.

It's because of trying to access web right after the zeppelin-daemon.sh run. but it take some time web server actually started and ready to serve.

This PR make it retry until the server it's ready to serve.

Ready to merge.

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
How about ppl that do not use FireFox?

**Comment by bzz** [comment]
:+1: merge 'em all!

Ppl with other browsers should be fine, as this tests are not a browser compatibility ones but integrational

**Comment by Leemoonsoo** [comment]
@anthonycorbacho 

on OSX, it does work only when FF is installed. (no success with Safari).
While this PR trying to fix different one, I think we can create separate issue for it.

Is it okay for you?

**Comment by corneadoug** [comment]
I think we should just use phantomjs in the future.... we would have less problems of web browser and it would be way faster :p

**Comment by anthonycorbacho** [comment]
okay,
But we should fix this issue ASAP.
For me it is really annoying to build Zeppelin and having 2000000 safari process open.

I can help to fix those if needed

**Comment by Leemoonsoo** [comment]
@anthonycorbacho 
Created an issue #304. it's cool if you help.

**Pull request merged**
