### PR TITLE
Migrating project website to ASF infra

### PR DESCRIPTION
**Pull request by bzz**
TODO:

 - [x] actualize current instructions
 - [x] document ASF deploy scenario
 - [x] update license\copyright
 - [x] linking ASF JIRA
 - [ ] ~~linking ASF git repo~~
 - [x] change name to "Apache Zeppelin (incubating)"
 - [x] add nav link back to Apache
 - [x] remove Copyright (at least until IP clearance sorted out)

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
Shouldn't we consider a version for Zeppelin website?
Like spark do with they documentation and the URL look like `incubator.apache.Zeppelin.org/latest/documentation` where latest is an alias to the last release of Zeppelin?

**Comment by bzz** [comment]
Good question!
 1. I think its a good idea to impl versioning but for API docs only 
 2. I do not think it's part of this PR scope though

**Comment by hsaputra** [comment]
Lets do versioning on APIs based on releases to make it easier for now

**Comment by bzz** [comment]
@hsaputra sounds great, +1 for making it on release
So after initial import of GH->JIRA issues I sugges we create such task and push it to first release scope

**Comment by bzz** [comment]
I think it is ready to merge.

screen shot 2015-01-26 at 15 04 46

and 

screen shot 2015-01-26 at 15 45 51

Source code change to ASF repo will be addressed separately.

**Comment by bzz** [comment]
Ready to be merged

**Comment by hsaputra** [comment]
+1 LGTM

**Comment by Leemoonsoo** [comment]
Tested locally - new menu, syntax highlighting and run command. 

LGTM

**Pull request merged**
